INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [10/Oct/2020 17:54:15] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /admin/student/ [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\engine\base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: student.proj1_accepted

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_admin\base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_admin\base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_admin\model\base.py", line 1969, in index_view
    count, data = self.get_list(view_args.page, sort_column, view_args.sort_desc,
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_admin\contrib\sqla\view.py", line 1079, in get_list
    query = query.all()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\orm\query.py", line 3246, in all
    return list(self)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\orm\query.py", line 3405, in __iter__
    return self._execute_and_instances(context)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\orm\query.py", line 3430, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\engine\base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\engine\base.py", line 1097, in _execute_clauseelement
    ret = self._execute_context(
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\engine\base.py", line 1287, in _execute_context
    self._handle_dbapi_exception(
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\engine\base.py", line 1481, in _handle_dbapi_exception
    util.raise_(
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\engine\base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: student.proj1_accepted
[SQL: SELECT student.id AS student_id, student.user_id AS student_user_id, student.title AS student_title, student.gender AS student_gender, student.dob AS student_dob, student.ppname AS student_ppname, student.surname AS student_surname, student.firstname AS student_firstname, student.prefname AS student_prefname, student.charname AS student_charname, student.birth_cntry AS student_birth_cntry, student.citizen_cntry AS student_citizen_cntry, student.street_addr AS student_street_addr, student.city_addr AS student_city_addr, student.state_addr AS student_state_addr, student.postcode_addr AS student_postcode_addr, student.cntry_addr AS student_cntry_addr, student.emg_name AS student_emg_name, student.emg_rel AS student_emg_rel, student.emg_ph AS student_emg_ph, student.uni_name AS student_uni_name, student.uni_majors AS student_uni_majors, student.uni_gpa AS student_uni_gpa, student.uni_years AS student_uni_years, student.uni_awards AS student_uni_awards, student.eng_prog AS student_eng_prog, student.eng_prog_choice AS student_eng_prog_choice, student.native_sp AS student_native_sp, student.test_sc AS student_test_sc, student.eng_file AS student_eng_file, student."longQ1" AS "student_longQ1", student."longQ2" AS "student_longQ2", student."longQ3" AS "student_longQ3", student."longQ4" AS "student_longQ4", student.cv_file AS student_cv_file, student.transcr_file AS student_transcr_file, student.tuition_fee AS student_tuition_fee, student.proj1_id AS student_proj1_id, student.proj1_pref AS student_proj1_pref, student.proj1_dur AS student_proj1_dur, student.proj1_accepted AS student_proj1_accepted, student.proj2_id AS student_proj2_id, student.proj2_pref AS student_proj2_pref, student.proj2_dur AS student_proj2_dur, student.proj2_accepted AS student_proj2_accepted, user_1.id AS user_1_id, user_1.name AS user_1_name, user_1.email AS user_1_email, user_1.confirmed AS user_1_confirmed, user_1.password AS user_1_password, user_1.role AS user_1_role, user_1.registered_on AS user_1_registered_on, user_1.confirmed_on AS user_1_confirmed_on, user_1.password_reset_token AS user_1_password_reset_token 
FROM student LEFT OUTER JOIN user AS user_1 ON user_1.id = student.user_id
 LIMIT ? OFFSET ?]
[parameters: (20, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
INFO:werkzeug:127.0.0.1 - - [10/Oct/2020 17:54:17] "[35m[1mGET /admin/student/ HTTP/1.1[0m" 500 -
