INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:00:06] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:00:09] "[37mGET /admin/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:00:10] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:00:11] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:00:12] "[37mGET /admin/supervisor/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:00:13] "[37mGET /admin/project/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:00:15] "[37mGET /admin/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:00:18] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:00:18] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:00:22] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:00:22] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:06:30] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:12:49] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:12:50] "[37mGET /auth/initial-registration HTTP/1.1[0m" 200 -
ERROR:app:Exception on /auth/initial-registration [POST]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\auth\routes.py", line 151, in initial_registration
    mail.send(msg)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 156, in configure_host
    host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 1034, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 1040, in _get_socket
    new_socket = socket.create_connection((host, port), timeout,
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\socket.py", line 808, in create_connection
    raise err
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:13:19] "[35m[1mPOST /auth/initial-registration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:13:33] "[37mGET /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:13:36] "[37mPOST /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:13:38] "[37mPOST /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:13:39] "[37mPOST /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:13:49] "[37mPOST /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:13:55] "[37mGET /admin/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:13:56] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:13:56] "[37mGET /admin/static/bootstrap/bootstrap3/swatch/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:14:19] "[32mPOST /admin/user/delete/ HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:14:19] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:14:22] "[37mGET /admin/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:14:27] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:14:28] "[37mGET /auth/initial-registration HTTP/1.1[0m" 200 -
ERROR:app:Exception on /auth/initial-registration [POST]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\auth\routes.py", line 151, in initial_registration
    mail.send(msg)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 156, in configure_host
    host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 1034, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 1040, in _get_socket
    new_socket = socket.create_connection((host, port), timeout,
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\socket.py", line 808, in create_connection
    raise err
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:14:52] "[35m[1mPOST /auth/initial-registration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:14:55] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:15:03] "[32mPOST /admin/user/delete/ HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:15:03] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:15:12] "[37mGET /auth/initial-registration HTTP/1.1[0m" 200 -
ERROR:app:Exception on /auth/initial-registration [POST]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\auth\routes.py", line 151, in initial_registration
    mail.send(msg)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 156, in configure_host
    host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 1034, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 1040, in _get_socket
    new_socket = socket.create_connection((host, port), timeout,
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\socket.py", line 808, in create_connection
    raise err
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:15:35] "[35m[1mPOST /auth/initial-registration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:16:23] "[37mGET /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:17:01] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:18:05] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:18:06] "[37mGET /admin/supervisor/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:18:07] "[37mGET /admin/project/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:18:09] "[37mGET /admin/project/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:18:12] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:18:31] "[37mGET /admin/user/edit/?id=1&url=%2Fadmin%2Fuser%2F HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:18:57] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:20:41] "[37mPOST /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:20:44] "[32mPOST /admin/user/delete/ HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:20:44] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:20:46] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:20:47] "[37mGET /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:20:57] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /auth/initial-registration [POST]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\auth\routes.py", line 151, in initial_registration
    mail.send(msg)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 156, in configure_host
    host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 1034, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 1040, in _get_socket
    new_socket = socket.create_connection((host, port), timeout,
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\socket.py", line 808, in create_connection
    raise err
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:21:13] "[35m[1mPOST /auth/initial-registration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:21:16] "[37mGET /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:21:25] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:21:26] "[37mGET /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:21:28] "[37mPOST /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:22:02] "[37mGET /admin/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:22:06] "[37mGET /myadmin/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:22:06] "[37mGET /static/admin-assets/admin_css.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:22:11] "[37mGET /myadmin/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:22:12] "[37mGET /myadmin/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:22:13] "[37mGET /myadmin/display/users/all/1 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:26:15] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:26:19] "[32mPOST /admin/user/delete/ HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:26:19] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:26:21] "[37mGET /myadmin/display/users/all/1 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:26:23] "[37mGET /myadmin/display/users/all/1 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:26:24] "[37mGET /myadmin/display/users/all/1 HTTP/1.1[0m" 200 -
ERROR:app:Exception on /auth/initial-registration [POST]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\auth\routes.py", line 151, in initial_registration
    mail.send(msg)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 156, in configure_host
    host = smtplib.SMTP_SSL(self.mail.server, self.mail.port)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 1034, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 1040, in _get_socket
    new_socket = socket.create_connection((host, port), timeout,
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\socket.py", line 808, in create_connection
    raise err
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 01:27:32] "[35m[1mPOST /auth/initial-registration HTTP/1.1[0m" 500 -
