INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [30/Sep/2020 10:22:16] "[32mGET / HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [30/Sep/2020 10:22:16] "[37mGET /supervisor/Cheng2 HTTP/1.1[0m" 200 -
ERROR:app:Exception on /edit-project/Cheng2 [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 345, in edit_project
    cur_user_projects = Project.query.filter_by(Project.user_id == super_id).all()
TypeError: filter_by() takes 1 positional argument but 2 were given
INFO:werkzeug:127.0.0.1 - - [30/Sep/2020 10:22:18] "[35m[1mGET /edit-project/Cheng2 HTTP/1.1[0m" 500 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [30/Sep/2020 10:22:18] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
