INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:03] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:03] "[37mGET /static/images/uwa_logo.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:03] "[37mGET /static/css/style.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:03] "[37mGET /static/images/favicon.ico HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:05] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:14] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:17] "[32mGET /admin HTTP/1.1[0m" 308 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:17] "[37mGET /admin/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:17] "[37mGET /admin/static/bootstrap/bootstrap3/swatch/default/bootstrap.min.css?v=3.3.5 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:17] "[37mGET /admin/static/bootstrap/bootstrap3/css/bootstrap-theme.min.css?v=3.3.5 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:17] "[37mGET /admin/static/admin/css/bootstrap3/admin.css?v=1.1.1 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:17] "[37mGET /admin/static/admin/css/bootstrap3/submenu.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:17] "[37mGET /admin/static/admin/js/helpers.js?v=1.0.0 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:17] "[37mGET /admin/static/bootstrap/bootstrap3/js/bootstrap.min.js?v=3.3.5 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:17] "[37mGET /admin/static/vendor/moment.min.js?v=2.22.2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:17] "[37mGET /admin/static/vendor/select2/select2.min.js?v=3.5.2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:17] "[37mGET /admin/static/vendor/jquery.min.js?v=3.3.1 HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:17] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:19] "[37mGET /admin/supervisor/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:19] "[37mGET /admin/static/admin/js/filters.js?v=1.0.0 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:19] "[37mGET /admin/static/admin/js/actions.js?v=1.0.0 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:19] "[37mGET /admin/static/vendor/bootstrap-daterangepicker/daterangepicker.js?v=1.3.22 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:19] "[37mGET /admin/static/admin/js/form.js?v=1.0.1 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:19] "[37mGET /admin/static/bootstrap/bootstrap3/swatch/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:19] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:23] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:23] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:33] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:33] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:43] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:43] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:48] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:48] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:50] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:57] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:57] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:38:59] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:00] "[37mGET /register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:03] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:13] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:19] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:19] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:30] "[32mGET /supervisor/Cheng HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:30] "[37mGET /login?next=%2Fsupervisor%2FCheng HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:33] "[37mGET /login?next=%2Fsupervisor%2FCheng HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:39] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:43] "[32mGET /supervisor/Cheng HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:43] "[37mGET /login?next=%2Fsupervisor%2FCheng HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:49] "[37mGET /login?next=%2Fsupervisor%2FCheng HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:49] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:50] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:39:51] "[37mGET /register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:40:32] "[32mPOST /register HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:40:32] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:40:36] "[37mGET /admin/supervisor/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:40:36] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:40:37] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:40:37] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:40:43] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:40:43] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:40:50] "[37mGET /admin/supervisor/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:40:50] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:40:50] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:40:50] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:40:59] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 00:40:59] "[37mGET /supervisor/Cheng2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:38] "[37mGET /add-project HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:38] "[37mGET /static/css/style.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:38] "[37mGET /static/images/uwa_logo.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:45] "[37mGET /admin/supervisor/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:45] "[37mGET /admin/static/bootstrap/bootstrap3/css/bootstrap-theme.min.css?v=3.3.5 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:45] "[37mGET /admin/static/bootstrap/bootstrap3/swatch/default/bootstrap.min.css?v=3.3.5 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:45] "[37mGET /admin/static/admin/css/bootstrap3/admin.css?v=1.1.1 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:45] "[36mGET /admin/static/vendor/select2/select2.css?v=3.5.2 HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:45] "[37mGET /admin/static/admin/css/bootstrap3/submenu.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:45] "[36mGET /admin/static/vendor/select2/select2-bootstrap3.css?v=1.4.6 HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:45] "[36mGET /admin/static/vendor/bootstrap-daterangepicker/daterangepicker-bs3.css?v=1.3.22 HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:45] "[37mGET /admin/static/admin/js/helpers.js?v=1.0.0 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:46] "[37mGET /admin/static/bootstrap/bootstrap3/js/bootstrap.min.js?v=3.3.5 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:46] "[37mGET /admin/static/vendor/bootstrap-daterangepicker/daterangepicker.js?v=1.3.22 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:46] "[37mGET /admin/static/vendor/moment.min.js?v=2.22.2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:46] "[37mGET /admin/static/vendor/select2/select2.min.js?v=3.5.2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:46] "[37mGET /admin/static/admin/js/form.js?v=1.0.1 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:46] "[37mGET /admin/static/admin/js/actions.js?v=1.0.0 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:46] "[37mGET /admin/static/admin/js/filters.js?v=1.0.0 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:46] "[37mGET /admin/static/vendor/jquery.min.js?v=3.3.1 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:46] "[37mGET /admin/static/bootstrap/bootstrap3/swatch/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:46] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:46] "[37mGET /admin/project/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:37:46] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:38:02] "[37mGET /supervisor/Cheng2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:38:04] "[37mGET /add-project HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:38:08] "[32mGET /index HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:38:08] "[37mGET /supervisor/Cheng2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:38:11] "[32mGET /logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:38:11] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:38:14] "[37mGET /register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:38:16] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:38:18] "[37mGET /register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:38:19] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:41:24] "[37mGET /register HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:28] "[32mPOST /register HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:28] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:32] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:33] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:38] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:38] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:40] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:40] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:41] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:41] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:47] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:47] "[37mGET /students/Bob HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:51] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:51] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:52] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:53] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:54] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:55] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:55] "[37mGET /admin/supervisor/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:55] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:56] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:56] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:57] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:42:57] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:44:12] "[37mGET /students/Bob/details HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:44:13] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:44:13] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:44:23] "[37mGET /students/Bob/details/page1 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:46:09] "[37mPOST /students/Bob/details/page2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:46:11] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:46:11] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:46:12] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:46:12] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:46:22] "[37mGET /students/Bob/details/page1 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:56:51] "[32mGET /index HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:56:51] "[37mGET /students/Bob HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:56:53] "[32mGET /logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:56:53] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:56:55] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:57:06] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:57:06] "[37mGET /supervisor/Cheng2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 08:57:17] "[37mGET /add-project HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:21:27] "[32mGET /index HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:21:27] "[37mGET /supervisor/Cheng2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:21:29] "[32mGET /logout HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:21:29] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:21:30] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:21:33] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:21:33] "[37mGET /students/Bob HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:21:38] "[37mGET /students/Bob/details HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:21:39] "[37mGET /students/Bob/details/page1 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:21:52] "[37mPOST /students/Bob/details/page2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:26:01] "[37mPOST /students/Bob/details/page3 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:26:07] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:26:07] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:28:13] "[37mPOST /students/Bob/details/page4 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:28:34] "[37mPOST /students/Bob/details/page5 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:28:45] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:28:45] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:31:06] "[37mPOST /students/Bob/details/page6 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:31:10] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:31:10] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:31:35] "[37mPOST /students/Bob/details/page6 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:31:37] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 32, in favicon
    return send_from_directory(os.path.join(app.root_path, 'static'),
NameError: name 'send_from_directory' is not defined
INFO:werkzeug:127.0.0.1 - - [15/Sep/2020 09:31:38] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
