INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on /supervisor-application [GET]
Traceback (most recent call last):
  File "c:\devtools\python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\devtools\python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\devtools\python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\devtools\python\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\devtools\python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\devtools\python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\David\GitHub Repos\CITS3200 Code\SDURI-Admin-Platform\app\routes.py", line 42, in supervisor_appl
    return render_template('application/supervisor/landing.html')
  File "c:\devtools\python\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\devtools\python\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\devtools\python\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\devtools\python\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\devtools\python\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\David\GitHub Repos\CITS3200 Code\SDURI-Admin-Platform\app\templates\application\supervisor\landing.html", line 3, in top-level template code
    {% extends "application/landing-base.html" %}
  File "c:\devtools\python\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\devtools\python\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\David\GitHub Repos\CITS3200 Code\SDURI-Admin-Platform\app\templates\application\landing-base.html", line 16, in template
    <form action="{% block start_url %}{% endblock %}/question1outof{% block max %}{% endblock %}">
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
INFO:werkzeug:127.0.0.1 - - [30/Aug/2020 15:03:14] "[35m[1mGET /supervisor-application HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2020 15:03:14] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [30/Aug/2020 15:03:17] "[37mGET / HTTP/1.1[0m" 200 -
